### ISSUE TITLE
Update file-type dependency to 16.5.4 for image-type@4.2.0

### ISSUE THREAD

**Issue by rafael-nogueras** [sindresorhus/image-type#20]
We are using image-type@4.1.0 (i.e. not 5.x) because we can not use an ESM module. However, image-type@4.1.0 has a dependency on file-type@10.10.0, which has a reported vulnerability.

Could we get an image-type@4.2.0 with an updated dependency on file-type@16.5.4, so we can keep using image-type pre-ESM? Thanks!

**Comment by sindresorhus** [comment]
I don't have any plans to do that (it's not even possible because of incompatible requireements). It's time to move to ESM.

And as documented here, you can use ESM from CommonJS using await: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by OfficialGhost321** [comment]
Wrong email I have the slightest clue what you’re talking abou yall been
emailing me all week

**Comment by rafael-nogueras** [comment]
I was afraid that would be the case. In any case, I thank you for the quick response!
