### ISSUE TITLE
Some files fail the check

### ISSUE THREAD

**Issue by codan84** [sindresorhus/image-type#21]
I have been using `image-type` for a while with great success. However, today I spotted that some files do not pass the check. Like [this one](https://www.propertyfinder.ae/property/ff905549921f7bf7290837418d80b1cb/1312/894/MODE/588a2a/9568812-c8c42o.jpg?ctr=ae)

I have downloaded it and run in node repl:
```
> let rawImage
> let imageType
> const downloadImgBuffer = url => fetch(url).then(res => res.arrayBuffer()).then(data => Buffer.from(data)).then(image => { rawImage = image })
> import('image-type').then(m => { imgType = m.default })
> downloadImgBuffer('https://www.propertyfinder.ae/property/ff905549921f7bf7290837418d80b1cb/1312/894/MODE/588a2a/9568812-c8c42o.jpg?ctr=ae)
> imgType(rawImage).then(res => console.log(`this is the res: "${JSON.stringify(res)}"`))
this is the res: "false"
```

Exactly the same code with other images works just fine, ie [this image](https://avatars.githubusercontent.com/u/9049379?v=11) correctly prints `this is the res: "{"ext":"jpg","mime":"image/jpeg"}"`.

Checking on another website that gives image type, extension, mime etc: https://www.checkfiletype.com/ and dragging over there the failing image above gives correct image type:
> File Type: image data, standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 1312x894, frames 3
MIME Type: image/jpeg;
Suggested file extension(s): jpg jpeg jpe jfif

Furthermore, according to documentation the `imageType` function is supposed to return `undefined` if it fails to establish image type, but by the looks of the above it returns `false`.

**Comment by sindresorhus** [comment]
Make sure your code is correct and that you are using the latest version of this package. I tried adding https://www.propertyfinder.ae/property/ff905549921f7bf7290837418d80b1cb/1312/894/MODE/588a2a/9568812-c8c42o.jpg?ctr=ae to the tests here and they still pass.

**Comment by codan84** [comment]
I am using the latest (5.2.0) version of the library:
```
"image-type": "^5.2.0",
```
Have you tried running this in repl like I did? I can't see anything wrong with my code...

I have tried with `--experimental-repl-await`:
```
> const { default: imageType } = await import('image-type')
> const getImageBuffer = url => fetch(url).then(res => res.arrayBuffer()).then(data => Buffer.from(data))
> let img = await getImageBuffer('https://avatars.githubusercontent.com/u/9049379?v=11')
> await imageType(img)
{ ext: 'jpg', mime: 'image/jpeg' }
> img = await getImageBuffer('https://www.propertyfinder.ae/property/ff905549921f7bf7290837418d80b1cb/1312/894/MODE/588a2a/9568812-c8c42o.jpg?ctr=ae')
> await imageType(img)
false
```

**Comment by sindresorhus** [comment]
If you log `img` as a string, you will see that it's HTML, not image data.
